{-|
Module          : Language.Snobol4.VM.Bytecode
Description     : Bytecode language
Copyright       : (c) Andrew Melnick 2016
License         : MIT
Maintainer      : meln5674@kettering.edu
Portability     : Unknown

TODO
-}

{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DefaultSignatures #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module Language.Snobol4.VM.Bytecode where

import Control.Monad

import Data.Serialize
import GHC.Generics

import Data.Map (Map)
import qualified Data.Map as M

import Data.Vector (Vector)
import qualified Data.Vector as V 

import Language.Snobol4.Interpreter.Data
import Language.Snobol4.Interpreter.Error
import Language.Snobol4.Interpreter.Internal.StateMachine
import Language.Snobol4.Syntax.AST

-- | Type used to reference unevaluated expressions
type ExprKey = SystemLabel

-- | An instruction with a label
data LabeledInstruction = LabeledInstruction Snobol4String Instruction

-- | A compiled program
newtype CompiledProgram = CompiledProgram { getCompiledProgram :: Vector Instruction }
  deriving Show

-- | A variable name, function name, or user defined label
newtype Symbol = Symbol { getSymbol :: Snobol4String }
  deriving (Show, Eq, Ord)

-- | A label generated by the compiler
newtype SystemLabel = SystemLabel Snobol4Integer
  deriving (Show, Eq, Ord, Enum, Num)

-- | Additional data accompanying a compiled program
data SymbolTable
    = SymbolTable
    { -- | Table of addresses of user defined labels
      userLabels :: Map Snobol4String Address
      -- | Table of address of compiler generated labels
    , systemLabels :: Map SystemLabel (Maybe Address)
      -- | Table of variable names
    , varSymbols :: Map Snobol4String Symbol
      -- | Table of function names
    , funcSymbols :: Map Snobol4String Symbol
      -- | Address of first instruction to execute
    , programEntryPoint :: Address
    }
  deriving Show

-- | Symbol table with no table entries and entry point is the first instruction
emptySymbolTable :: SymbolTable
emptySymbolTable
    = SymbolTable
      M.empty
      M.empty
      M.empty
      M.empty
      (Address 0)


-- | A bytecode instruction.
-- Constructors are documented using the following format:
-- vN : Pop N items from the stack
-- $N : Reference the Nth item popped from the stack (1-based)
-- ^X : Push X onto the stack
-- !N : Reference the Nth argument of the constructor (1-based)
-- X; Y : Do X, then do Y
-- X ? Y : Z : If X, then do Y, else do Z
-- X := Y : Set X to the value of Y
data Instruction
    = 
    -- | Push a string onto the stack
      PushString Snobol4String
    -- | Push an integer onto the stack
    | PushInteger Snobol4Integer
    -- | Push a real onto the stack
    | PushReal Snobol4Real
    -- | Push a reference to a variable onto the stack
    | PushReference Snobol4String
    -- | Push a reference to a keyword onto the stack
    | PushReferenceKeyword Snobol4String
    -- | Push a reference to a array/table onto the stack
    -- This instruction assumes that there are sufficient arguments already on the stack
    | PushReferenceAggregate Snobol4String Snobol4Integer
    -- | Push a reference to the input variable onto the stack
    | PushReferenceInput
    -- | Push a reference to the output variable onto the stack
    | PushReferenceOutput
    -- | Push a reference to the punch variable onto the stack
    | PushReferencePunch
    -- | Push the entry point of an unevaluated expression onto the stack
    | PushExpression SystemLabel
    -- | Pop the top value off of the stack
    | Pop
    -- | Make N copies of the top value of the stack, including the current instance
    | Copy Int
    -- | Reverse the order of the top two items on the stack
    | Rotate
    
    {-
    -- | Pop the top two items, push their sum
    | Add
    -- | Pop the top two items, push their difference
    | Subtract
    -- | Pop the top two items, push their product
    | Multiply
    -- | Pop the top two items, push their quotient
    | Divide
    -- | Pop the top two items, push their exponentiation
    | Exponentiate

    -- | Pop the top two items, push their concatenation
    | ConcatString
    -- | Pop the top two items, push a pattern 
    | ConcatPattern
    -- | v2; ^($2 | $1)
    | AlternatePattern
    
    -- | v2; ($2 > $1) ? ^1 : ^0
    | GreaterThan
    -- | v2; ($2 >= $1) ? ^1 : ^0
    | GreaterThanOrEqualTo
    -- | v2; ($2 < $1) ? ^1 : ^0
    | LessThan
    -- | v2; ($2 <= $1) ? ^1 : ^0
    | LessThanOrEqualTo
    -- | v2; ($2 == $1) ? ^1 : ^0
    | Equal
    -- | v2; ($2 /= $1) ? ^1 : ^0
    | NotEqual
    
    
    
    -- TODO: Rest of the patterns
    -- | v2; ^(AssignmentPattern $2 $1)
    | PrimitiveAssignmentPattern
    -- | v2; ^(ImmediateAssignmentPattern $2 $1)
    | PrimitiveImmediateAssignmentPattern
    -- | v1; ^(LiteralPattern $1)
    | PrimitiveLiteralPattern
    -- etc
    -- | v1; ^(AssignmentPattern $1)
    | PrimitiveAnyPattern
    -- etc
    -}
    
    
    -- | Pop the top item off the stack, and push the value of the variable with
    -- that name
    | LookupDynamic
    -- | Push the value of the given variable
    | LookupStatic Symbol
    -- | Pop the specified number of arguments off the stack and push the entry
    -- of the given variable at those indices
    | LookupStaticRef Symbol Int
    -- | Push the value of the given keyword
    | LookupStaticKeyword Symbol
    
    -- | Pop the top item off the stack and assign the given variable to it
    | AssignStatic Symbol
    -- | Pop the top item off the stack and assign the given keyword to it
    | AssignStaticKeyword Symbol
    -- | Pop the top item off the stack, followed by N arguments, and assign the
    -- entry in the given variable indexed by the arguments to the top item
    | AssignRefStatic Symbol Int
    -- | Pop the top two items off the stack, assign the variable pointed to by
    -- the first to the second
    | AssignDynamic

    {-
    -- | v2; Create a new function using $1 as the entry label and $2 as the prototype
    | Define
    -- | ???
    | CallDynamic
    -}
    -- | Call the specified functions with N arguments currently on the stack.
    -- Also specifies if the call should be treated as an LValue
    | CallStatic Symbol Int Bool
    {-
    -- | ^(arg count)
    | GetArgCount
    -}
    -- | Return from the current function call successfully
    | Return
    -- | Return from the current function call unsuccessfully
    | FReturn
    -- | Return from the current function call successfully with the return
    -- value translated into a reference
    | NReturn

    -- | Return from an unevaluated expression
    | ExprReturn

    
    -- | Overwrite the system label to jump to on failure
    | SetFailLabel SystemLabel
    -- | Push the current failure label onto the stack and then overwrite it
    | PushFailLabel SystemLabel
    -- | Overwrite the failure label by popping off the stack
    | PopFailLabel
    -- | Jump to the failure label
    | JumpToFailureLabel
    
    {-
    -- | v1; $1 == 0 || $1 == "" ? Jump to the failure label : noop
    | JumpToFailureLabelIf
    -- | v1; $1 == 0 || $1 == "" ? noop : Jump to the failure label
    | JumpToFailureLabelElse
    -}

    -- | Jump to a compiler defined label
    | JumpStatic SystemLabel
    
    {-
    -- | v1; $1 == 0 || $1 == "" ? Jump to !1 : noop
    | JumpStaticIf SystemLabel
    -- | v1; $1 == 0 || $1 == "" ? noop : Jump to !1
    | JumpStaticElse SystemLabel
    -}
    
    -- | Pop a label off the stack and jump to the user defined label with that
    -- name
    | JumpDynamic
    -- | Pop a label off the stack and jump to the generated code object with
    -- that name
    | DirectJump
    
    -- | Call the synonym for the given binary operator
    | BinOp Operator
    -- | Call the synonym for the given unary operator
    | UnOp Operator
    
    -- | Invoke the scanner
    | InvokeScanner
    -- | Invoke the replacer
    | InvokeReplacer

    {-    
    -- | v1; $1 is stringable ? ^(string $1) : ^failure
    | ConvertToString
    -- | v1; $1 is integerable ? ^(integer $1) : ^failure
    | ConvertToInteger
    -- | v1; $1 is realable ? ^(real $1) : ^failure
    | ConvertToReal
    -- | v1; $1 is patternable ? ^(pattern $1) : ^failure
    | ConvertToPattern
    -}
    
    {-
    -- | v2; Invoke the array allocator using $1 as the initial value, and $2 as
    -- the prototype
    | AllocArray
    -- | v1; Invoke the table allocator using $1 as the initial size
    | AllocTable
    -}

    -- | Panic with the given error
    | Panic ProgramError
    -- | Terminate the program successfully
    | Finish

    -- | Read from input and push it onto the stack
    | Input
    -- | Pop the top item off the stack and write it to output
    | Output
    -- | Pop the top item off the stack and punch it
    | Punch
    
    -- | Push the last item written to output onto the stack  
    | LastOutput
    -- | Push the last item punched onto the stack
    | LastPunch
  deriving (Show)

deriving instance Serialize Address
deriving instance Generic SymbolTable
deriving instance Generic Operator
deriving instance Generic ProgramError
deriving instance Generic SystemLabel
deriving instance Generic Symbol
deriving instance Generic Instruction

instance Serialize a => Serialize (Vector a) where
    get = liftM V.fromList get
    put = put . V.toList

instance Serialize Snobol4String where
    put = put . (unmkString :: Snobol4String -> String)
    get = liftM mkString (get :: Get String)

instance Serialize Snobol4Integer where
    put = put . (unmkInteger :: Snobol4Integer -> Int)
    get = liftM mkInteger (get :: Get Int)

instance Serialize Snobol4Real where
    put = put . (unmkReal :: Snobol4Real -> Float)
    get = liftM mkReal (get :: Get Float)

instance Serialize Operator
instance Serialize ProgramError
instance Serialize SystemLabel
instance Serialize Symbol
instance Serialize Instruction
instance Serialize SymbolTable

deriving instance Serialize CompiledProgram
